const fs = require('fs');
const path = require('path');

const envFile = path.join(__dirname, '../.env');
const targetFile = path.join(__dirname, '../src/environments/environment.ts');
const templateFile = path.join(__dirname, '../src/environments/environment.template.ts');

// Create environment.ts from template if it doesn't exist
if (!fs.existsSync(targetFile) && fs.existsSync(templateFile)) {
  fs.copyFileSync(templateFile, targetFile);
}

let token = process.env['TMDB_BEARER_TOKEN'] || '';
let openAiKey = process.env['OPENAI_API_KEY'] || '';

if (!token && fs.existsSync(envFile)) {
  const envContent = fs.readFileSync(envFile, 'utf8');
  const tmdbMatch = envContent.match(/TMDB_BEARER_TOKEN=(.+)/);
  if (tmdbMatch) token = tmdbMatch[1].trim();
  const openAiMatch = envContent.match(/OPENAI_API_KEY=(.+)/);
  if (openAiMatch) openAiKey = openAiMatch[1].trim();
}

if (!token) {
  console.error('\x1b[31m%s\x1b[0m', '❌ Error: TMDB_BEARER_TOKEN is not set');
  console.log('\x1b[33m%s\x1b[0m', '⚠️  Set it as an environment variable or add it to .env');
  process.exit(1);
}

const content = `// This file is auto-generated by scripts/load-env.js
// DO NOT edit manually - changes will be overwritten
// To update variables, edit .env file and run npm start or npm build

export const environment = {
  tmdbBearerToken: '${token}',
  openAiKey: '${openAiKey}'
};
`;

fs.writeFileSync(targetFile, content);
console.log('\x1b[32m%s\x1b[0m', '✅ Environment variables loaded successfully');
